import Marquee from '@/components/marquee'
import ProjectCard from '@/components/projectCard'
import { Press_Start_2P } from 'next/font/google'

const p2p = Press_Start_2P({weight: "400", subsets: ['latin']})

export interface Project {
    name: string,
    imgsrc: string,
    description: string,
    tools: string[]
}

const projects:Project[] = [
    {
        name: "DegenerateAssets",
        imgsrc: "/DegenAssets.jpeg",
        description: "Built a full web application for just-for-fun gambling games. Users could log in, earn and lose coins, and compete against others on the leaderboard!",
        tools: ["React", "Express", "Python", "MongoDB", "Docker", "Digital Ocean"]
    },
    {
        name: "Image Stitching",
        imgsrc: "/ImageStitch.jpeg",
        description: "Built an image processing pipeline that ingested a random assortment of images, programatically discovered keypoints of interest between the group of images (if any), calculated the homography between images, and algorithmically stitched and blended the overlapping images into a single panorama.",
        tools: ["Python", "OpenCV"]
    },
    {
        name: "Content Generator",
        imgsrc: "/ContentGen.jpeg",
        description: "Developed a series of Python and Bash scripts that automatically generated video-content from sample code generated by ChatGPT. The sample code would be copied into a .py file, a code editing tool would be opened and a screen recording would begin. Next, the scripts simulated typing the generated code character by character until completion, then the screen recording was exported mashed with a random splicing of a longer audio clip, and directly posted to TikTok.",
        tools: ["Python", "Linux"]
    },
    {
        name: "NFL Spread Predictions",
        imgsrc: "/NFLPreds.jpeg",
        description: "Built a website that posted a trained model's predictions of NFL games and the model's certainty. Found the best performing regression model by training with XGBoost, CatBoost, and LightGBM models with hyperparameters tuned using a grid search algorithm on each.",
        tools: ["Python", "ML", "XGBoost", "SKLearn"]
    },
    {
        name: "Driver's License Reader",
        imgsrc: "/DLReader.jpeg",
        description: "Built a website that allowed users to submit photos of a driver's license and returned the JSON of the extracted data. Performed a perspective transformation and cropped the image to get a more useful top down angle on the license. Utilized feautre matching to extract the target content from the license and output into a JSON model.",
        tools: ["React", "Express", "Python", "OpenCV"]
    },
    {
        name: "Portfolio Site",
        imgsrc: "/Portfolio.jpeg",
        description: "Built this portfolio website filled with responsive elements and interactive animations. :)",
        tools: ["Tailwind", "NextJS", "TypeScript"]
    },
]

const marquee_items = ["Spring", "Git", "Postman", "Docker", "Kubernetes", "Terraform", "Jenkins"]

export default function ProjectSection() {
    return (
        <div id="projects">
            <div className="flex justify-center items-center p-4 w-full h-24">
                <h1 className={`text-4xl ${p2p.className}`}>Projects</h1>
            </div>
            <div className="grid lg:grid-cols-3 md:grid-cols-2 grid-cols-1">
                {projects.map((project) => (
                    <div key="" className="flex justify-center items-center p-4 w-full h-96">
                        <ProjectCard name={project.name} imgsrc={project.imgsrc} description={project.description} tools={project.tools}/>
                    </div>
                ))}
            </div>
            <div className='h-24'>
                <Marquee items={marquee_items}/>
            </div>
        </div>
    )
}