export const portfolioData = {
  name: "Lars Fyhr",
  location: "Austin, TX",
  tagline: "I am not a front end developer and I made this! Imagine what I can build for you!",

  about: "Hi! My name is Lars Fyhr. I love to ski, wakesurf, bike, golf, and play soccer. I enjoy exploring the world to experience new cultures and cuisines. I grew up in Houston, TX and graduated from the University of Texas at Austin (hook 'em) with a BS in Electrical/Computer Engineering. I would love to go back to school to further my education. I am currently located in Austin, TX working at Oracle. My interests include computer vision, quantitative finance, automation, and machine learning.",

  headshot: "/Headshot.jpg",
  heroImage: "/coding-freak.gif",

  skills: ["ML", "AI", "Python", "Kotlin", "TypeScript", "Java", "C++", "Linux"],
  tools: ["Spring", "Git", "Postman", "Docker", "Kubernetes", "Terraform", "Jenkins"],

  navLinks: ["Home", "About", "Projects", "Connect"],

  experience: [
    {
      name: "Started Coding",
      image: "/events/Start.png",
      year: "2016",
    },
    {
      name: "Golden Section Ventures",
      image: "/events/GSV.png",
      year: "2019",
    },
    {
      name: "Ping Identity",
      image: "/events/Ping.png",
      year: "2021",
    },
    {
      name: "UT Austin",
      image: "/events/UTAustin.png",
      year: "2022",
    },
    {
      name: "Oracle",
      image: "/events/Oracle.png",
      year: "2022",
    },
  ],

  projects: [
    {
      name: "DegenerateAssets",
      image: "/DegenAssets.jpeg",
      description: "Built a full web application for just-for-fun gambling games. Users could log in, earn and lose coins, and compete against others on the leaderboard!",
      tools: ["React", "Express", "Python", "MongoDB", "Docker", "Digital Ocean"],
    },
    {
      name: "Image Stitching",
      image: "/ImageStitch.jpeg",
      description: "Built an image processing pipeline that ingested a random assortment of images, programatically discovered keypoints of interest between the group of images (if any), calculated the homography between images, and algorithmically stitched and blended the overlapping images into a single panorama.",
      tools: ["Python", "OpenCV"],
    },
    {
      name: "Content Generator",
      image: "/ContentGen.jpeg",
      description: "Developed a series of Python and Bash scripts that automatically generated video-content from sample code generated by ChatGPT. The sample code would be copied into a .py file, a code editing tool would be opened and a screen recording would begin. Next, the scripts simulated typing the generated code character by character until completion, then the screen recording was exported mashed with a random splicing of a longer audio clip, and directly posted to TikTok.",
      tools: ["Python", "Linux"],
    },
    {
      name: "NFL Spread Predictions",
      image: "/NFLPreds.jpeg",
      description: "Built a website that posted a trained model's predictions of NFL games and the model's certainty. Found the best performing regression model by training with XGBoost, CatBoost, and LightGBM models with hyperparameters tuned using a grid search algorithm on each.",
      tools: ["Python", "ML", "XGBoost", "SKLearn"],
    },
    {
      name: "Driver's License Reader",
      image: "/DLReader.jpeg",
      description: "Built a website that allowed users to submit photos of a driver's license and returned the JSON of the extracted data. Performed a perspective transformation and cropped the image to get a more useful top down angle on the license. Utilized feautre matching to extract the target content from the license and output into a JSON model.",
      tools: ["React", "Express", "Python", "OpenCV"],
    },
    {
      name: "Portfolio Site",
      image: "/Portfolio.jpeg",
      description: "Built this portfolio website filled with responsive elements and interactive animations. :)",
      tools: ["Tailwind", "NextJS", "TypeScript"],
    },
  ],

  connect: [
    {
      name: "Email",
      icon: "/icons/Email.png",
      link: "",
      handle: "fyhr_lars [at] yahoo [dot] com",
    },
    {
      name: "LinkedIn",
      icon: "/icons/LI.png",
      link: "https://www.linkedin.com/in/lars-fyhr/",
      handle: "@lars-fyhr",
    },
    {
      name: "GitHub",
      icon: "/icons/GH.png",
      link: "https://www.github.com/lcfyhr/",
      handle: "@lcfyhr",
    },
  ],
} as const;

export type PortfolioData = typeof portfolioData;
export type Project = (typeof portfolioData.projects)[number];
export type Experience = (typeof portfolioData.experience)[number];
export type ConnectItem = (typeof portfolioData.connect)[number];
